### ISSUE TITLE
Support for issuing prepared statements?

### ISSUE THREAD

**Issue by awinder** [wvanbergen/node-vertica#24]
Vertica supports prepared statements as a means of optimizing queries and providing some convenience / security benefits as of the 6.x branch (https://my.vertica.com/docs/6.1.x/HTML/index.htm#11677.htm).  Is this supported in node-vertica?  I saw some use of the string "prepared_statement" in the FrontendMessage class, but I was having trouble groking how this would be used (or if it was even applicable).

**Comment by amirtuval** [comment]
Hi Guys

I'm testing Vertica's performance, and I think having prepared statements - even without parameters - may improve performance for my use case.

Can you provide some pointers on how to implement prepared statements with the given protocol? 

Thanks

**Comment by wvanbergen** [comment]
It should follow the PostgreSQL protocol: https://www.postgresql.org/docs/9.2/static/protocol-overview.html#PROTOCOL-QUERY-CONCEPTS

I managed to get it to work for 0 parameters, but when using parameters it would fail. I assume this has not changed.

**Comment by amirtuval** [comment]
I was able to get it to work - I investigated how the vertica jdbc driver does it.
Sent a [pull request for it](https://github.com/wvanbergen/vertica/pull/56).
