### ISSUE TITLE
Connection error on node.js version >= 0.11.3

### ISSUE THREAD

**Issue by dalex3** [wvanbergen/node-vertica#36]
I get error when connecting to server with node.js v0.11.3 and up

```javascript
vertica.connect({host:'127.0.0.1', user:'...', password:'...'}, function(err){
    console.log(err);
});

{ [Error: Invalid startup packet layout: expected terminator as last byte]
  message: 'Invalid startup packet layout: expected terminator as last byte',
  fields: 
   { Severity: 'FATAL',
     Code: '08V01',
     Message: 'Invalid startup packet layout: expected terminator as last byte',
     File: '/scratch_a/release/vbuild/vertica/Session/ClientSession.cpp',
     Line: '3800',
     Routine: 'ProcessStartupPacket' },
  code: '08V01' }
```

**Comment by wvanbergen** [comment]
@sudhakar Thanks for fixing this issue.

**Comment by sudhakar** [comment]
@wvanbergen Big thanks to you for this library. I have been using this in production for more than a year & super happy with its stability :sparkles:

**Comment by wvanbergen** [comment]
I am no longer using this library myself. I have added you as a collaborator so you can fix issues if you run into any. Feel free to ping me for code reviews if you want to.

**Comment by sudhakar** [comment]
Awesome @wvanbergen. I missed to update the package.json on the last PR. Have updated & pushed in the last commit. Can you publish 0.5.3 to npm..

**Comment by wvanbergen** [comment]
Release is pushed. Can you check if it's working as expected?
