### ISSUE TITLE
insert SQL does not work

### ISSUE THREAD

**Issue by peakpado** [wvanbergen/node-vertica#42]
I run SQL to insert values and the query runs without error, but the values are not inserted to the database.

**Comment by wvanbergen** [comment]
Did you run a `COMMIT` afterwards?

**Comment by peakpado** [comment]
No, I couldn't find any commit method in the API. Is this 'COMMIT' SQL?

**Comment by wvanbergen** [comment]
Yes, in SQL you always have to COMMIT any changes (unless your database does autocommit, but Vertica doesn't do that)

**Comment by wvanbergen** [comment]
just run `connection.query('commit')` after your inserts.
