### ISSUE TITLE
Empty resultset .rows

### ISSUE THREAD

**Issue by ColorfullyMe** [wvanbergen/node-vertica#43]
Maybe this is not an issue but more like a question but could please advise why `resultset.rows`  and `Raw` are returned as empty array/never called? I am sure the table contains data and running the same query from the vsql gives the expected results. Vertica runs locally on VM via VMWare player.

The code I try to use is:
```js
var Vertica, connection;

Vertica = require('vertica');

connection = Vertica.connect({
    user: "...",
    password: '...',
    database: "...",
    host: '192.168.0.104'
}, function (err) {
    var query;
    if (err) {
        throw err;
    }
    query = connection.query("SELECT * FROM nypd_motor_vehicle_collisions LIMIT 5");
    query.on('fields', function (fields) {
        return console.log("Fields:", fields);
    });
    query.on('row', function (row) {
        return console.log('Row:', row);
    });
    query.on('end', function (status) {
        return console.log("Finished!", status);
    });
    query.on('error', function (err) {
        return console.error("Error!", err);
    });
    return connection.query("SELECT * FROM nypd_motor_vehicle_collisions LIMIT 5", function (err, resultset) {
        return console.log('Query', err, resultset.fields, resultset.rows, resultset.status);
    });
});
```

`row` event never gets triggered nor is the `Query` console.log getting `resultset.rows` as anything else but empty array.

**Comment by sudhakar** [comment]
Are there any errors thrown in console? Is ```fields``` event getting fired with fields list?
Try setting ```connection.debug=true``` to get more details

**Comment by ColorfullyMe** [comment]
@sudhakar No `error` event triggered but `fields` event gets fired correctly and the fields returned are correct as expected. Enabling debug does not help. Same thing only little more info at the end. Hope it will help to guide me in the right direction.
```text
<= CommandComplete { status: 'SELECT' }
Finished! SELECT
<= ReadyForQuery { transactionStatus: 84 }
```

**Comment by sudhakar** [comment]
Thats wired. Are you sure you are not exiting the process before the query is complete (some where by explicitly calling ```process.exit()``` )

Try narrowing it down by using only the buffered version & isolating it to a separate file. RowDescription should be followed by DataRow before ```CommandComplete```. If not, most likely there arent any selectable rows in that DB.

**Comment by wvanbergen** [comment]
Yeah, this looks to me like the database is simply returning an empty resultset. can you try with the query `SELECT 1`?

**Comment by mikearo** [comment]
I have an issue similar to the one above using the "node-vertica" package. An empty resultset for every row was returned. Fields returned as expected as well as "end". I have tried using a "node-jdbc" package. And I get a similar behaviour. 

HP Vertica DB/Analytics Platform Version:  7.1.x
Type: Community edition, without license
NodeJS version: 0.12.0
Node-vertica version: The latest one in the repo using "npm install vertica"
OS version: Ubuntu 14.04 LTS
Virtual machine version: Parallels 10
Host OS: OS X 10.9.5
Machine: Mac Book Pro [2.6 GHz Intel Core i7, 16 GB DDR3]

Using SELECT 1, I got the output below

Fields: [ { name: '?column?',
    tableOID: 0,
    tableFieldIndex: 0,
    typeOID: 6,
    type: 'integer',
    size: 8,
    modifier: 4294967295,
    formatCode: 0,
    decoder: [Function] } ]
[ 1 ]

It actually returned the "1" as a value.

Advise?

**Comment by wvanbergen** [comment]
Not sure. This looks like something on the server side to me - the client does exactly what you expect it to do based on the messages the server is sending. Maybe this is a permissions or settings thing?

The only thing I can think of is the Vertica version. This package is tested against Vertica 7.0; maybe something has changed for 7.1? Unfortunately I do not have access to Vertica 7.1 myself at the moment.

**Comment by mikearo** [comment]
Thanks - You are right. I figured out it's a server side issue. Tested against another vertica database. It worked. Agreed, it  could be a settings or permissions thing.

**Comment by wvanbergen** [comment]
Closing this. Please let me know if you find out the issue on the server's end.

**Comment by mikearo** [comment]
Finally found a solution via this link: http://stackoverflow.com/questions/27164238/why-does-vsql-can-return-all-the-records-while-program-using-odbc-driver-cant

Before loading an sql data script with INSERT statements, I set the AUTOCOMMIT ON in the Vsql client.

Like so:

STEP 1a: \set AUTOCOMMIT on
STEP 1b: Press Enter

STEP 2a: [db]=>\i data.sql
STEP 2b: Press Enter

**Comment by wvanbergen** [comment]
Yes, in Vertica you have to `COMMIT` in order for inserted/updated/deleted data to take effect. If you're using node-vertica to insert data, you can also do `connection.query('COMMIT")` after inserting data.
