### ISSUE TITLE
Support Copy Command

### ISSUE THREAD

**Issue by maxstudener** [wvanbergen/node-vertica#52]
Are you going to be adding support for vertica's copy command like you did in your ruby implantation?

**Comment by wvanbergen** [comment]
No, I will not work on this myself, because I don't work in either Javascript software, not Vertica infrastructure anymore.

I'll gladly accept PRs though.

**Comment by maxstudener** [comment]
Ok I will look into seeing if I can find some time into making a pull request, as i might need this for a project I am working on.
