### ISSUE TITLE
"multi-queries" error is not caught

### ISSUE THREAD

**Issue by spillevink** [wvanbergen/node-vertica#54]
Error: `Uncaught exception: Error: Cannot handle multi-queries with a callback!`
To reproduce: `delete from foo; delete from foo;`

This error should be in a callback so we can catch it.

**Comment by wvanbergen** [comment]
I think this is a good idea, but it's unlikely that I will work on this any time soon. PRs are welcome though.

**Comment by spillevink** [comment]
@wvanbergen: PR #55 submitted

**Comment by spillevink** [comment]
@wvanbergen: Is a new release planned now that #55 is merged?

**Comment by wvanbergen** [comment]
Let me see if I still know how to do that :)

**Comment by wvanbergen** [comment]
@spillevink Looks like I don't have a working node setup anymore. If you want to, I can add you as a collaborator, and let you do the release yourself.

**Comment by spillevink** [comment]
That would be great, thank you!

**Comment by wvanbergen** [comment]
What is your npm username?

**Comment by spillevink** [comment]
[jts](https://www.npmjs.com/~jts)

**Comment by wvanbergen** [comment]
Added!

**Comment by spillevink** [comment]
Thank you!
