### ISSUE TITLE
Maintenance - next steps for this library

### ISSUE THREAD

**Issue by gregjopa** [wvanbergen/node-vertica#58]
I'm interested in helping maintain this library. The company I work for (YP) uses Vertica and has been evaluating this module. I have been going through the source code trying to understand how the integration works with Vertica. I realize this module does not use ODBC or VSQL or any standard Vertica driver. Instead, it opens a socket connection to Vertica and sends/receives binary data (frontend_message.coffee and backend_message.coffee).  Is there any documentation available about the protocol this module uses to talk to Vertica?

**Comment by spillevink** [comment]
Sorry for the late response!

It seems to be basically the same protocol as postgres, so that documentation should be pretty much correct.

Some vertica-specific features like SHA256 are not documented and thus not supported by this library.

**Comment by wvanbergen** [comment]
Hello, @gregjopa. Thanks for showing interest in helping maintaining this gem. I don't use it myself anymore, so it's always good to have some other people helping out instead. I added you as a collaborator.

@spillevink is right about the protocol. I used the PostgreSQL documentation to get 95% there. The other 5% I figured out by trial and error.

**Comment by gregjopa** [comment]
Thanks for adding me as a collaborator! We are actively using this module at YP and I look forward to contributing to this project.
